
name: customer_management
description: A Flutter application for managing customers.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floor: ^1.4.2
  sqflite: ^2.2.8+4
  shared_preferences: ^2.1.1
  shared_preferences_android: ^2.1.4
  intl: ^0.19.0
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/tr.json