name: vehicle_maintenance_app
description: A Flutter app for tracking vehicle maintenance records.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # SQLite database (Floor)
  floor: ^1.5.0
  path_provider: ^2.1.1
  path: ^1.9.0

  # EncryptedSharedPreferences
  shared_preferences: ^2.2.2

  # Localization (optional)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Optional: Add ARB files for localization
  # assets:
  #   - lib/l10n/
